### ISSUE TITLE
What's the best way to add Markdown extensions (not filters)?

### ISSUE THREAD

**Issue by matthew-brett** [class4kayaker/pelican_pandoc_reader#3]
I found myself wanting to add the `footnotes` Markdown extension to the basic Pandoc Markdown default extensions.

The way to do this on the Pandoc command line is add the extensions to the Markdown flavor, as in:

```
pandoc -f markdown+footnotes mypost.pdc -o mypost.html
```

I see the `PANDOC_EXTENSION` configuration variable, but I think this is not what I want, because it adds stuff to the `--filter` command line, not to the Markdown flavor.   It might be better if that variable was called `PANDOC_FILTERS` or similar.

What would be the best way of adding / removing Markdown extensions from the default input format?   At the moment I do something a bit ugly in my `pelicanconf.py`:

```
# Set pandoc markdown flavor
sys.path.append(pjoin('plugins', 'pelican_pandoc_reader'))
import pelican_pandoc_reader as pdr
pdr.pandoc_fmt_map['pdc'] = 'markdown+footnotes'
```

**Comment by class4kayaker** [comment]
Not sure, I had mostly designed this with options that I ended up needing for personal use, so a new configuration variable would likely be needed. Your suggested modification to the name for the filter, and the addition of a new configuration variable might be the best option.

**Comment by class4kayaker** [comment]
In 295f13d, I have added a new setting that allows the specification of the mapping of the file extensions to the Pandoc format specifiers. This should both handle your specified problem, and allow the modification of the list of formats handled by the reader much more easily.

**Comment by matthew-brett** [comment]
Great - yes - that looks like a good solution.
